---
abstract: 'Module to store files in a DBI backend'
author:
  - 'joshr <joshr@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-FileStore
requires:
  Config::File: 0
  DBI: 0
  Digest::MD5: 0
  File::Copy: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
version: 0.23
