--- #YAML:1.0
name:               DBIx-FileStore
version:            0.13
abstract:           Module to store files in a DBI backend
author:
    - joshr <joshr>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::File:         0
    DBD::mysql:           0
    DBI:                  0
    Digest::MD5:          0
    File::Copy:           0
    File::Spec::Functions:  0
    File::Temp:           0
    List::Util:           0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
